In [2]:
import pandas as pd

df=pd.read_excel("EC 490 Project Dataset State obs.xlsx", usecols="A:v")

In [3]:
df = df.rename(columns={"Gini ": "Gini"})

In [4]:
print(df)

             State  Population    Year  # Buglary  # Larcenry    # MVT  \
0          Alabama   4785298.0  2010.0    37009.0         NaN      NaN
1           Alaska    713985.0  2010.0        NaN         NaN      NaN
2          Arizona   6413737.0  2010.0        NaN         NaN      NaN
3         Arkansas   2921606.0  2010.0        NaN         NaN      NaN
4       California  37349363.0  2010.0        NaN         NaN      NaN
..             ...         ...     ...        ...         ...      ...
659     Washington   7958180.0  2024.0    32135.0    130915.0  34634.0
660  West Virginia   1769979.0  2024.0     3122.0     14610.0   1356.0
661      Wisconsin   5960975.0  2024.0     7495.0     51397.0   9706.0
662        Wyoming    587618.0  2024.0      934.0      5416.0    590.0
663            NaN         NaN     NaN        NaN         NaN      NaN

     Aggregate  div by pop  Property Crime Rate    Gini  ...  Unemp_Rate  \
0          NaN         NaN          3516.800000  0.4720  ...        11.8
1          NaN         NaN          2852.500000  0.4220  ...         9.6
2          NaN         NaN          3534.000000  0.4550  ...        11.8
3          NaN         NaN          3558.900000  0.4580  ...         9.6
4          NaN         NaN          2635.800000  0.4710  ...        12.8
..         ...         ...                  ...     ...  ...         ...
659   197684.0         NaN          2484.035295  0.4725  ...         4.9
660    19088.0         NaN          1078.430874  0.4668  ...         4.6
661    68598.0         NaN          1150.784897  0.4419  ...         3.1
662     6940.0         NaN          1181.039383  0.4609  ...         3.4
663        NaN         NaN                  NaN     NaN  ...         NaN

     Pct_SP_HH  Pct_NonWhite  Land Area  Pop_Density  Young_Male    S   MW  \
0    31.709485          30.5    50645.0    94.487077    5.094186    1    0
1    22.946922          32.6   570641.0     1.251198    5.582330    0    0
2    26.812403          20.6   113594.0    56.461935    5.144676    0    0
3    30.204388          21.6    52035.0    56.146940    5.005021    1    0
4    23.472537          37.6   155779.0   239.758652    5.501336    0    0
..         ...           ...        ...          ...         ...  ...  ...
659  19.049343          36.0    66456.0   119.751114    4.425484    0    0
660  26.311590          10.6    24038.0    73.632540    4.511183    1    0
661  22.989078          20.4    54158.0   110.066380    4.760161    0    1
662  21.623611          16.7    97093.0     6.052115    5.018737    0    0
663        NaN           NaN        NaN          NaN         NaN  221  156

      NE    W
0      0    0
1      0    1
2      0    1
3      0    0
4      0    1
..   ...  ...
659    0    1
660    0    0
661    0    0
662    0    1
663  117  169

[664 rows x 22 columns]

In [5]:
df.head()

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.8,0.472,...,11.8,31.709485,30.5,50645.0,94.487077,5.094186,1,0,0,0
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.5,0.422,...,9.6,22.946922,32.6,570641.0,1.251198,5.582330,0,0,0,1
2,Arizona,6413737.0,2010.0,NaN,NaN,NaN,NaN,NaN,3534.0,0.455,...,11.8,26.812403,20.6,113594.0,56.461935,5.144676,0,0,0,1
3,Arkansas,2921606.0,2010.0,NaN,NaN,NaN,NaN,NaN,3558.9,0.458,...,9.6,30.204388,21.6,52035.0,56.146940,5.005021,1,0,0,0
4,California,37349363.0,2010.0,NaN,NaN,NaN,NaN,NaN,2635.8,0.471,...,12.8,23.472537,37.6,155779.0,239.758652,5.501336,0,0,0,1

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State                663 non-null    str
 1   Population           663 non-null    float64
 2   Year                 663 non-null    float64
 3   # Buglary            154 non-null    float64
 4   # Larcenry           153 non-null    float64
 5   # MVT                153 non-null    float64
 6   Aggregate            153 non-null    float64
 7   div by pop           0 non-null      float64
 8   Property Crime Rate  663 non-null    float64
 9   Gini                 663 non-null    float64
 10  Pov_Rate             663 non-null    float64
 11  Med_Income           663 non-null    float64
 12  Unemp_Rate           663 non-null    float64
 13  Pct_SP_HH            663 non-null    float64
 14  Pct_NonWhite         663 non-null    float64
 15  Land Area            663 non-null    float64
 16  Pop_Density          663 non-null    float64
 17  Young_Male           663 non-null    float64
 18  S                    664 non-null    int64
 19  MW                   664 non-null    int64
 20  NE                   664 non-null    int64
 21  W                    664 non-null    int64
dtypes: float64(17), int64(4), str(1)
memory usage: 114.3 KB

In [7]:
df.columns

Index(['State', 'Population', 'Year', '# Buglary', '# Larcenry', '# MVT',
       'Aggregate', 'div by pop', 'Property Crime Rate', 'Gini', 'Pov_Rate',
       'Med_Income', 'Unemp_Rate', 'Pct_SP_HH', 'Pct_NonWhite', 'Land Area',
       'Pop_Density', 'Young_Male', 'S', 'MW', 'NE', 'W'],
      dtype='str')

In [8]:
len(df["State"])

664

In [9]:
df[["State", "Property Crime Rate"]]

             State  Property Crime Rate
0          Alabama          3516.800000
1           Alaska          2852.500000
2          Arizona          3534.000000
3         Arkansas          3558.900000
4       California          2635.800000
..             ...                  ...
659     Washington          2484.035295
660  West Virginia          1078.430874
661      Wisconsin          1150.784897
662        Wyoming          1181.039383
663            NaN                  NaN

[664 rows x 2 columns]

Finding row 1, property crime columns.

In [10]:
df.iloc[1]["Property Crime Rate"]

np.float64(2852.5)

In [11]:
df[df["State"] == "Alabama"]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.800000,0.4720,...,11.8,31.709485,30.5,50645.0,94.487077,5.094186,1,0,0,0
51,Alabama,4802740.0,2011.0,NaN,NaN,NaN,NaN,NaN,3606.100000,0.4735,...,11.6,31.240079,30.9,50645.0,94.831474,5.095654,1,0,0,0
102,Alabama,4822023.0,2012.0,NaN,NaN,NaN,NaN,NaN,3502.200000,0.4726,...,10.0,31.840922,30.9,50645.0,95.212222,5.119760,1,0,0,0
153,Alabama,4833722.0,2013.0,NaN,NaN,NaN,NaN,NaN,3351.300000,0.4752,...,9.6,32.958558,31.1,50645.0,95.443222,5.213084,1,0,0,0
204,Alabama,4849377.0,2014.0,NaN,NaN,NaN,NaN,NaN,3177.600000,0.4758,...,8.6,32.451903,31.5,50645.0,95.752335,5.053639,1,0,0,0
255,Alabama,4858979.0,2015.0,NaN,NaN,NaN,NaN,NaN,2978.900000,0.4811,...,7.2,31.675058,31.5,50645.0,95.941929,4.850649,1,0,0,0
306,Alabama,4863300.0,2016.0,NaN,NaN,NaN,NaN,NaN,2947.800000,0.4847,...,6.4,30.062710,31.8,50645.0,96.027248,4.745091,1,0,0,0
357,Alabama,4874747.0,2017.0,NaN,NaN,NaN,NaN,NaN,2957.300000,0.4768,...,5.8,32.500581,32.0,50645.0,96.253273,4.813747,1,0,0,0
408,Alabama,4887871.0,2018.0,NaN,NaN,NaN,NaN,NaN,2817.200000,0.4859,...,5.6,29.468417,32.3,50645.0,96.512410,4.784742,1,0,0,0
459,Alabama,4903185.0,2019.0,NaN,NaN,NaN,NaN,NaN,2674.400000,0.4741,...,4.9,29.355676,32.2,50645.0,96.814789,4.622465,1,0,0,0
510,Alabama,5076181.0,2022.0,13995.0,60102.0,9821.0,83918.0,NaN,1653.171942,0.4851,...,4.3,29.073865,34.9,50645.0,100.230645,4.829103,1,0,0,0
561,Alabama,5117673.0,2023.0,13054.0,62932.0,10358.0,86344.0,NaN,1687.173057,0.4771,...,4.0,31.358505,35.3,50645.0,101.049916,4.716013,1,0,0,0
612,Alabama,5157699.0,2024.0,13869.0,59985.0,9174.0,83028.0,NaN,1609.787620,0.4745,...,4.2,31.222725,36.0,50645.0,101.840241,4.662157,1,0,0,0

In [12]:
df[(df["Property Crime Rate"] < 3000) & (df["State"] == "Alabama")]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
255,Alabama,4858979.0,2015.0,NaN,NaN,NaN,NaN,NaN,2978.900000,0.4811,...,7.2,31.675058,31.5,50645.0,95.941929,4.850649,1,0,0,0
306,Alabama,4863300.0,2016.0,NaN,NaN,NaN,NaN,NaN,2947.800000,0.4847,...,6.4,30.062710,31.8,50645.0,96.027248,4.745091,1,0,0,0
357,Alabama,4874747.0,2017.0,NaN,NaN,NaN,NaN,NaN,2957.300000,0.4768,...,5.8,32.500581,32.0,50645.0,96.253273,4.813747,1,0,0,0
408,Alabama,4887871.0,2018.0,NaN,NaN,NaN,NaN,NaN,2817.200000,0.4859,...,5.6,29.468417,32.3,50645.0,96.512410,4.784742,1,0,0,0
459,Alabama,4903185.0,2019.0,NaN,NaN,NaN,NaN,NaN,2674.400000,0.4741,...,4.9,29.355676,32.2,50645.0,96.814789,4.622465,1,0,0,0
510,Alabama,5076181.0,2022.0,13995.0,60102.0,9821.0,83918.0,NaN,1653.171942,0.4851,...,4.3,29.073865,34.9,50645.0,100.230645,4.829103,1,0,0,0
561,Alabama,5117673.0,2023.0,13054.0,62932.0,10358.0,86344.0,NaN,1687.173057,0.4771,...,4.0,31.358505,35.3,50645.0,101.049916,4.716013,1,0,0,0
612,Alabama,5157699.0,2024.0,13869.0,59985.0,9174.0,83028.0,NaN,1609.787620,0.4745,...,4.2,31.222725,36.0,50645.0,101.840241,4.662157,1,0,0,0

In [13]:
df[(df["Property Crime Rate"] < 2000) | (df["State"] == "Alabama")]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.800000,0.4720,...,11.8,31.709485,30.5,50645.0,94.487077,5.094186,1,0,0,0
12,Idaho,1571450.0,2010.0,NaN,NaN,NaN,NaN,NaN,1995.800000,0.4330,...,10.0,20.545193,7.8,82643.0,19.014920,4.997995,0,0,0,1
32,New York,19392283.0,2010.0,NaN,NaN,NaN,NaN,NaN,1941.200000,0.4990,...,9.9,28.516380,34.1,47126.0,411.498599,5.198625,0,0,1,0
34,North Dakota,674499.0,2010.0,NaN,NaN,NaN,NaN,NaN,1768.500000,0.4330,...,3.9,20.918295,10.0,69001.0,9.775206,6.466429,0,1,0,0
41,South Dakota,816463.0,2010.0,NaN,NaN,NaN,NaN,NaN,1852.400000,0.4420,...,6.0,23.526971,14.0,75811.0,10.769717,5.235877,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,Vermont,648493.0,2024.0,863.0,9457.0,426.0,10746.0,NaN,1657.072628,0.4551,...,2.7,21.875729,9.9,9217.0,70.358360,4.826729,0,0,1,0
658,Virginia,8811195.0,2024.0,9683.0,116963.0,12850.0,139496.0,NaN,1583.167777,0.4691,...,3.6,23.023772,40.7,39490.0,223.124715,4.846505,1,0,0,0
660,West Virginia,1769979.0,2024.0,3122.0,14610.0,1356.0,19088.0,NaN,1078.430874,0.4668,...,4.6,26.311590,10.6,24038.0,73.632540,4.511183,1,0,0,0
661,Wisconsin,5960975.0,2024.0,7495.0,51397.0,9706.0,68598.0,NaN,1150.784897,0.4419,...,3.1,22.989078,20.4,54158.0,110.066380,4.760161,0,1,0,0
662,Wyoming,587618.0,2024.0,934.0,5416.0,590.0,6940.0,NaN,1181.039383,0.4609,...,3.4,21.623611,16.7,97093.0,6.052115,5.018737,0,0,0,1

In [14]:
df[df["State"].isin(["North Carolina", "South Carolina"])]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
33,North Carolina,9561558.0,2010.0,NaN,NaN,NaN,NaN,NaN,3447.300000,0.4640,...,12.7,28.934748,30.3,48618.0,196.667037,5.085395,1,0,0,0
40,South Carolina,4636312.0,2010.0,NaN,NaN,NaN,NaN,NaN,3900.400000,0.4610,...,12.8,33.065272,32.9,30061.0,154.230132,5.302447,1,0,0,0
84,North Carolina,9656401.0,2011.0,NaN,NaN,NaN,NaN,NaN,3526.800000,0.4716,...,11.7,29.878589,29.9,48618.0,198.617816,5.127635,1,0,0,0
91,South Carolina,4679230.0,2011.0,NaN,NaN,NaN,NaN,NaN,3904.200000,0.4648,...,11.9,31.458812,33.0,30061.0,155.657829,5.331839,1,0,0,0
135,North Carolina,9752073.0,2012.0,NaN,NaN,NaN,NaN,NaN,3369.500000,0.4691,...,10.8,28.620042,30.1,48618.0,200.585647,5.134672,1,0,0,0
142,South Carolina,4723723.0,2012.0,NaN,NaN,NaN,NaN,NaN,3822.200000,0.4684,...,11.2,33.249579,33.0,30061.0,157.137920,5.352473,1,0,0,0
186,North Carolina,9848060.0,2013.0,NaN,NaN,NaN,NaN,NaN,3128.000000,0.4765,...,9.7,29.367859,30.8,48618.0,202.559957,5.266540,1,0,0,0
193,South Carolina,4774839.0,2013.0,NaN,NaN,NaN,NaN,NaN,3624.200000,0.4665,...,9.5,31.990985,32.8,30061.0,158.838329,5.331908,1,0,0,0
237,North Carolina,9943964.0,2014.0,NaN,NaN,NaN,NaN,NaN,2873.100000,0.4748,...,8.3,28.509798,30.9,48618.0,204.532560,5.166531,1,0,0,0
244,South Carolina,4832482.0,2014.0,NaN,NaN,NaN,NaN,NaN,3460.300000,0.4687,...,8.1,32.482045,32.7,30061.0,160.755863,5.246724,1,0,0,0
288,North Carolina,10042802.0,2015.0,NaN,NaN,NaN,NaN,NaN,2750.100000,0.4776,...,6.9,27.530988,30.9,48618.0,206.565511,5.205768,1,0,0,0
295,South Carolina,4896146.0,2015.0,NaN,NaN,NaN,NaN,NaN,3293.300000,0.4698,...,7.3,31.416786,32.8,30061.0,162.873690,5.113941,1,0,0,0
339,North Carolina,10146788.0,2016.0,NaN,NaN,NaN,NaN,NaN,2737.500000,0.4780,...,6.2,28.035490,31.1,48618.0,208.704348,4.927875,1,0,0,0
346,South Carolina,4961119.0,2016.0,NaN,NaN,NaN,NaN,NaN,3243.800000,0.4735,...,6.3,31.056221,32.6,30061.0,165.035062,4.904317,1,0,0,0
390,North Carolina,10273419.0,2017.0,NaN,NaN,NaN,NaN,NaN,2545.300000,0.4763,...,5.3,27.024953,31.2,48618.0,211.308960,4.987969,1,0,0,0
397,South Carolina,5024369.0,2017.0,NaN,NaN,NaN,NaN,NaN,3195.900000,0.4795,...,5.8,31.855142,32.7,30061.0,167.139117,4.949378,1,0,0,0
441,North Carolina,10383620.0,2018.0,NaN,NaN,NaN,NaN,NaN,2494.100000,0.4782,...,5.0,27.452787,31.6,48618.0,213.575630,4.895701,1,0,0,0
448,South Carolina,5084127.0,2018.0,NaN,NaN,NaN,NaN,NaN,3017.600000,0.4762,...,5.3,30.573386,33.0,30061.0,169.127008,5.009946,1,0,0,0
492,North Carolina,10488084.0,2019.0,NaN,NaN,NaN,NaN,NaN,2357.300000,0.4743,...,4.6,27.823120,31.9,48618.0,215.724300,4.993953,1,0,0,0
499,South Carolina,5148714.0,2019.0,NaN,NaN,NaN,NaN,NaN,2940.300000,0.4747,...,4.7,30.626349,33.3,30061.0,171.275540,4.751012,1,0,0,0
543,North Carolina,10710793.0,2022.0,38880.0,157080.0,20873.0,216833.0,NaN,2024.434605,0.4768,...,3.8,27.053538,37.8,48618.0,220.305093,4.968449,1,0,0,0
550,South Carolina,5287935.0,2022.0,19342.0,90809.0,13340.0,123491.0,NaN,2335.335060,0.4757,...,4.4,29.085157,36.4,30061.0,175.906823,4.904031,1,0,0,0
594,North Carolina,10881189.0,2023.0,37089.0,154623.0,28232.0,219944.0,NaN,2021.323221,0.4732,...,4.0,25.721422,38.6,48618.0,223.809885,4.899289,1,0,0,0
601,South Carolina,5387830.0,2023.0,17601.0,88228.0,13951.0,119780.0,NaN,2223.158489,0.4715,...,4.3,28.921962,36.4,30061.0,179.229899,4.609034,1,0,0,0
645,North Carolina,11046024.0,2024.0,34653.0,149604.0,27466.0,211723.0,NaN,1916.734927,0.4782,...,4.0,25.607336,39.2,48618.0,227.200296,4.852280,1,0,0,0
652,South Carolina,5478831.0,2024.0,15537.0,80898.0,11872.0,108307.0,NaN,1976.826808,0.4662,...,4.5,27.578785,36.8,30061.0,182.257111,4.736229,1,0,0,0

Calling where state = NC in 2024

In [15]:
df[(df["State"] == "North Carolina") & (df["Year"] == 2024)]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
645,North Carolina,11046024.0,2024.0,34653.0,149604.0,27466.0,211723.0,NaN,1916.734927,0.4782,...,4.0,25.607336,39.2,48618.0,227.200296,4.85228,1,0,0,0

Grouping state, property crime rate order by descending

In [16]:
df.groupby("State")["Property Crime Rate"].mean().sort_values(ascending=False)

State
District of Columbia    4498.816063
New Mexico              3398.082369
Washington              3295.203090
Louisiana               3159.343779
South Carolina          3149.040027
Arkansas                3067.737776
Hawaii                  2915.615268
Tennessee               2909.370649
Oregon                  2908.980987
Oklahoma                2877.669970
Arizona                 2848.370365
Alabama                 2806.133278
Texas                   2798.168689
Missouri                2785.325226
Georgia                 2773.457937
Colorado                2709.377330
Alaska                  2707.572412
North Carolina          2707.037904
Delaware                2645.609679
Kansas                  2631.941442
Nevada                  2567.285481
Utah                    2552.637984
Florida                 2510.941905
Ohio                    2476.803863
California              2465.009162
Mississippi             2361.831361
Indiana                 2355.041039
Maryland                2346.232567
Montana                 2345.221228
Nebraska                2237.871357
Minnesota               2178.945605
Kentucky                2093.925948
Illinois                2059.988524
North Dakota            2016.055552
Michigan                1963.258693
Iowa                    1911.195317
Rhode Island            1892.391280
Virginia                1887.359776
Wisconsin               1858.382587
Wyoming                 1844.146666
South Dakota            1810.939271
West Virginia           1797.611172
Connecticut             1797.418065
Vermont                 1780.285629
Maine                   1760.139670
Pennsylvania            1759.533681
New York                1690.908802
New Jersey              1658.171783
Massachusetts           1622.882138
New Hampshire           1608.732216
Idaho                   1545.657519
Name: Property Crime Rate, dtype: float64

In [17]:
df.groupby("State")["Gini"].mean().sort_values(ascending=False)

State
District of Columbia    0.526738
New York                0.511500
Connecticut             0.495585
Louisiana               0.490869
California              0.486392
Massachusetts           0.483631
Florida                 0.483569
Mississippi             0.479631
Texas                   0.478608
Illinois                0.478608
Georgia                 0.478546
Alabama                 0.477569
New Mexico              0.476854
New Jersey              0.476838
Tennessee               0.476085
Kentucky                0.474654
North Carolina          0.474508
Arkansas                0.472054
Pennsylvania            0.470669
Rhode Island            0.470523
South Carolina          0.470500
Virginia                0.468354
Oklahoma                0.466785
West Virginia           0.465977
Michigan                0.464254
Arizona                 0.464154
Ohio                    0.463938
Missouri                0.462454
Oregon                  0.458592
Nevada                  0.458408
Colorado                0.457808
Washington              0.457731
Montana                 0.455092
Kansas                  0.454608
North Dakota            0.453969
Maryland                0.452138
Maine                   0.451569
Delaware                0.450469
Indiana                 0.450346
Minnesota               0.449031
Vermont                 0.446885
Nebraska                0.445031
South Dakota            0.444138
Wisconsin               0.442854
Idaho                   0.441146
Hawaii                  0.440838
Iowa                    0.439962
New Hampshire           0.438885
Wyoming                 0.433777
Alaska                  0.425508
Utah                    0.424715
Name: Gini, dtype: float64

In [18]:
df.describe()["Property Crime Rate"]

count     663.000000
mean     2399.012943
std       746.592355
min       748.244296
25%      1855.950000
50%      2327.600000
75%      2885.550000
max      5182.500000
Name: Property Crime Rate, dtype: float64

df.loc[rows, columns]
df.loc[0]  (header)

In [19]:
df.loc[6, ["State", "Property Crime Rate"]]

State                  Connecticut
Property Crime Rate         2193.2
Name: 6, dtype: object

In [20]:
df[df["Property Crime Rate"] > 4000]

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Unemp_Rate,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W
8,District of Columbia,604453.0,2010.0,NaN,NaN,NaN,NaN,NaN,4778.900000,0.5320,...,12.4,44.795192,59.8,61.0,9909.065574,6.374689,1,0,0,0
59,District of Columbia,617996.0,2011.0,NaN,NaN,NaN,NaN,NaN,4795.500000,0.5338,...,11.4,50.955145,60.1,61.0,10131.081967,6.157160,1,0,0,0
110,District of Columbia,632323.0,2012.0,NaN,NaN,NaN,NaN,NaN,4860.800000,0.5343,...,10.3,45.931060,60.4,61.0,10365.950820,6.069208,1,0,0,0
161,District of Columbia,646449.0,2013.0,NaN,NaN,NaN,NaN,NaN,4808.300000,0.5320,...,10.4,43.538016,59.1,61.0,10597.524590,5.917868,1,0,0,0
212,District of Columbia,658893.0,2014.0,NaN,NaN,NaN,NaN,NaN,5182.500000,0.5224,...,8.9,45.904799,59.8,61.0,10801.524590,5.667081,1,0,0,0
263,District of Columbia,672228.0,2015.0,NaN,NaN,NaN,NaN,NaN,4676.200000,0.5354,...,7.3,43.204370,60.0,61.0,11020.131148,5.535176,1,0,0,0
314,District of Columbia,681170.0,2016.0,NaN,NaN,NaN,NaN,NaN,4802.900000,0.5420,...,6.9,44.641103,59.3,61.0,11166.721311,5.284877,1,0,0,0
365,District of Columbia,693972.0,2017.0,NaN,NaN,NaN,NaN,NaN,4283.900000,0.5281,...,6.6,39.372966,59.0,61.0,11376.590164,4.915040,1,0,0,0
416,District of Columbia,702455.0,2018.0,NaN,NaN,NaN,NaN,NaN,4373.800000,0.5243,...,7.5,41.710965,57.8,61.0,11515.655738,4.875472,1,0,0,0
467,District of Columbia,705749.0,2019.0,NaN,NaN,NaN,NaN,NaN,4367.100000,0.5115,...,6.3,41.098046,57.5,61.0,11569.655738,4.622890,1,0,0,0
569,District of Columbia,687324.0,2023.0,1671.0,20338.0,7425.0,29434.0,NaN,4282.405387,0.5163,...,5.3,39.250692,61.2,61.0,11267.606557,4.482806,1,0,0,0

Grab same as above, but only show those column.

In [21]:
df[(df["Gini"] > 0.5) & (df["Property Crime Rate"] > 4000)][["State" , "Property Crime Rate", "Gini"]]

                    State  Property Crime Rate    Gini
8    District of Columbia          4778.900000  0.5320
59   District of Columbia          4795.500000  0.5338
110  District of Columbia          4860.800000  0.5343
161  District of Columbia          4808.300000  0.5320
212  District of Columbia          5182.500000  0.5224
263  District of Columbia          4676.200000  0.5354
314  District of Columbia          4802.900000  0.5420
365  District of Columbia          4283.900000  0.5281
416  District of Columbia          4373.800000  0.5243
467  District of Columbia          4367.100000  0.5115
569  District of Columbia          4282.405387  0.5163

Creating new column where high vs medium/low crime

In [22]:
import numpy as np

df["Newcolumn"] = np.where(df["Property Crime Rate"] > 4000, "High Crime", "Medium or low Crime")
df.head()

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W,Newcolumn
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.8,0.472,...,31.709485,30.5,50645.0,94.487077,5.094186,1,0,0,0,Medium or low Crime
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.5,0.422,...,22.946922,32.6,570641.0,1.251198,5.582330,0,0,0,1,Medium or low Crime
2,Arizona,6413737.0,2010.0,NaN,NaN,NaN,NaN,NaN,3534.0,0.455,...,26.812403,20.6,113594.0,56.461935,5.144676,0,0,0,1,Medium or low Crime
3,Arkansas,2921606.0,2010.0,NaN,NaN,NaN,NaN,NaN,3558.9,0.458,...,30.204388,21.6,52035.0,56.146940,5.005021,1,0,0,0,Medium or low Crime
4,California,37349363.0,2010.0,NaN,NaN,NaN,NaN,NaN,2635.8,0.471,...,23.472537,37.6,155779.0,239.758652,5.501336,0,0,0,1,Medium or low Crime

Removing new column

In [23]:

df = df.drop(columns=["Newcolumn"])

Creating new column with 3 choices.

In [24]:
conditions = [
    (df["Property Crime Rate"] >= 2500), 
    (df["Property Crime Rate"] <2500) & (df["Property Crime Rate"] >= 1500),
    (df["Property Crime Rate"] < 1500),
]

choices = ["High Crime", "Medium Crime", "Low Crime"] 

df["Crime Level"] = np.select(conditions, choices, default="Unknown")

df.head()

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Pct_SP_HH,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W,Crime Level
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.8,0.472,...,31.709485,30.5,50645.0,94.487077,5.094186,1,0,0,0,High Crime
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.5,0.422,...,22.946922,32.6,570641.0,1.251198,5.582330,0,0,0,1,High Crime
2,Arizona,6413737.0,2010.0,NaN,NaN,NaN,NaN,NaN,3534.0,0.455,...,26.812403,20.6,113594.0,56.461935,5.144676,0,0,0,1,High Crime
3,Arkansas,2921606.0,2010.0,NaN,NaN,NaN,NaN,NaN,3558.9,0.458,...,30.204388,21.6,52035.0,56.146940,5.005021,1,0,0,0,High Crime
4,California,37349363.0,2010.0,NaN,NaN,NaN,NaN,NaN,2635.8,0.471,...,23.472537,37.6,155779.0,239.758652,5.501336,0,0,0,1,High Crime

Another faster way to add a new column with IFELSE

In [25]:
df["Gini Level"] = df["Gini"].apply(lambda x: "High Inequality" if x > 0.45 else "Medium Inequality" if x > 0.30 else "Low Inequality")
df.head()

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Pct_NonWhite,Land Area,Pop_Density,Young_Male,S,MW,NE,W,Crime Level,Gini Level
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.8,0.472,...,30.5,50645.0,94.487077,5.094186,1,0,0,0,High Crime,High Inequality
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.5,0.422,...,32.6,570641.0,1.251198,5.582330,0,0,0,1,High Crime,Medium Inequality
2,Arizona,6413737.0,2010.0,NaN,NaN,NaN,NaN,NaN,3534.0,0.455,...,20.6,113594.0,56.461935,5.144676,0,0,0,1,High Crime,High Inequality
3,Arkansas,2921606.0,2010.0,NaN,NaN,NaN,NaN,NaN,3558.9,0.458,...,21.6,52035.0,56.146940,5.005021,1,0,0,0,High Crime,High Inequality
4,California,37349363.0,2010.0,NaN,NaN,NaN,NaN,NaN,2635.8,0.471,...,37.6,155779.0,239.758652,5.501336,0,0,0,1,High Crime,High Inequality

Creating a new column using if elif else

In [26]:
def UnemploymentLevel(row):
    if row["Unemp_Rate"] > 7:
        return "High Unemployment"
    elif row["Unemp_Rate"] > 4:
        return "Medium Unemployment"
    else:
        return "Low Unemployment"
    
df["Unemployment Level"] = df.apply(UnemploymentLevel, axis=1)

df.head()

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Land Area,Pop_Density,Young_Male,S,MW,NE,W,Crime Level,Gini Level,Unemployment Level
0,Alabama,4785298.0,2010.0,37009.0,NaN,NaN,NaN,NaN,3516.8,0.472,...,50645.0,94.487077,5.094186,1,0,0,0,High Crime,High Inequality,High Unemployment
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.5,0.422,...,570641.0,1.251198,5.582330,0,0,0,1,High Crime,Medium Inequality,High Unemployment
2,Arizona,6413737.0,2010.0,NaN,NaN,NaN,NaN,NaN,3534.0,0.455,...,113594.0,56.461935,5.144676,0,0,0,1,High Crime,High Inequality,High Unemployment
3,Arkansas,2921606.0,2010.0,NaN,NaN,NaN,NaN,NaN,3558.9,0.458,...,52035.0,56.146940,5.005021,1,0,0,0,High Crime,High Inequality,High Unemployment
4,California,37349363.0,2010.0,NaN,NaN,NaN,NaN,NaN,2635.8,0.471,...,155779.0,239.758652,5.501336,0,0,0,1,High Crime,High Inequality,High Unemployment

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 664 entries, 0 to 663
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   State                663 non-null    str
 1   Population           663 non-null    float64
 2   Year                 663 non-null    float64
 3   # Buglary            154 non-null    float64
 4   # Larcenry           153 non-null    float64
 5   # MVT                153 non-null    float64
 6   Aggregate            153 non-null    float64
 7   div by pop           0 non-null      float64
 8   Property Crime Rate  663 non-null    float64
 9   Gini                 663 non-null    float64
 10  Pov_Rate             663 non-null    float64
 11  Med_Income           663 non-null    float64
 12  Unemp_Rate           663 non-null    float64
 13  Pct_SP_HH            663 non-null    float64
 14  Pct_NonWhite         663 non-null    float64
 15  Land Area            663 non-null    float64
 16  Pop_Density          663 non-null    float64
 17  Young_Male           663 non-null    float64
 18  S                    664 non-null    int64
 19  MW                   664 non-null    int64
 20  NE                   664 non-null    int64
 21  W                    664 non-null    int64
 22  Crime Level          664 non-null    str
 23  Gini Level           664 non-null    str
 24  Unemployment Level   664 non-null    str
dtypes: float64(17), int64(4), str(4)
memory usage: 129.8 KB

In [47]:

df["Crime Level"].value_counts()

Crime Level
Medium Crime    300
High Crime      292
Low Crime        71
Name: count, dtype: int64

In [66]:
df.groupby(["Year"]).agg({"Property Crime Rate": "mean", "Unemp_Rate": "mean", "Gini": "mean"})

        Property Crime Rate  Unemp_Rate      Gini
Year
2010.0          2894.003922    9.950980  0.453765
2011.0          2883.403922    9.392157  0.458347
2012.0          2854.333333    8.543137  0.459184
2013.0          2739.943137    7.790196  0.464227
2014.0          2603.501961    6.741176  0.463649
2015.0          2514.331373    5.919608  0.465675
2016.0          2504.064706    5.509804  0.466361
2017.0          2414.625490    5.070588  0.465949
2018.0          2246.178431    4.747059  0.468008
2019.0          2141.198039    4.392157  0.464165
2022.0          1877.483119    3.970588  0.469410
2023.0          1832.251585    3.949020  0.467404
2024.0          1681.849239    4.252941  0.465690

In [71]:
df["YOY Property Crime Rate Change"] = df.groupby("State")["Property Crime Rate"].pct_change() * 100

In [72]:
df.sample(10)

,State,Population,Year,# Buglary,# Larcenry,# MVT,Aggregate,div by pop,Property Crime Rate,Gini,...,Pop_Density,Young_Male,S,MW,NE,W,Crime Level,Gini Level,Unemployment Level,YOY Property Crime Rate Change
14,Indiana,6490621.0,2010.0,NaN,NaN,NaN,NaN,NaN,3042.400000,0.4400,...,181.170686,5.131096,0,1,0,0,High Crime,Medium Inequality,High Unemployment,NaN
275,Maryland,6006401.0,2015.0,NaN,NaN,NaN,NaN,NaN,2315.000000,0.4524,...,618.770063,4.716934,1,0,0,0,Medium Crime,High Inequality,Medium Unemployment,-7.676969
463,California,39512223.0,2019.0,NaN,NaN,NaN,NaN,NaN,2331.200000,0.4866,...,253.642808,4.788617,0,0,0,1,Medium Crime,High Inequality,Medium Unemployment,-2.066880
82,New Mexico,2082224.0,2011.0,NaN,NaN,NaN,NaN,NaN,3531.500000,0.4821,...,17.166186,5.232962,0,0,0,1,High Crime,High Inequality,High Unemployment,2.797345
531,Massachusetts,7022468.0,2022.0,10123.0,58118.0,6964.0,75205.0,NaN,1070.919796,0.4976,...,900.316410,4.982846,0,0,1,0,Low Crime,High Inequality,Medium Unemployment,-9.228700
331,Missouri,6093000.0,2016.0,NaN,NaN,NaN,NaN,NaN,2799.100000,0.4646,...,88.635769,4.943575,0,1,0,0,High Crime,High Inequality,Medium Unemployment,-1.930488
1,Alaska,713985.0,2010.0,NaN,NaN,NaN,NaN,NaN,2852.500000,0.4220,...,1.251198,5.582330,0,0,0,1,High Crime,Medium Inequality,High Unemployment,NaN
118,Kansas,2885905.0,2012.0,NaN,NaN,NaN,NaN,NaN,3143.200000,0.4496,...,35.297704,5.460713,0,1,0,0,High Crime,Medium Inequality,Medium Unemployment,2.048635
89,Pennsylvania,12742886.0,2011.0,NaN,NaN,NaN,NaN,NaN,2222.300000,0.4611,...,284.801779,5.049413,0,0,1,0,Medium Crime,High Inequality,High Unemployment,2.268753
556,Virginia,8683414.0,2022.0,11146.0,123957.0,13999.0,149102.0,NaN,1717.089615,0.4755,...,219.888934,4.961963,1,0,0,0,Medium Crime,High Inequality,Low Unemployment,4.528497